#14 フッターの実装（Footerコンポーネント）
kougakusai/kougakusai-hp pull request #20
Opened 2021-10-16 13:02 UTC by minusvoid

概ね昨年度のデザインを踏襲したデザインで完成
ページリンクは、ページがそろったのちに追記

2021-10-16 15:16 UTC, kazuhiro-f commented on src/components/modules/Footer/Footer.tsx
> +        ["k-lg:text-[1.35rem]", "k-lg:py-[5%]", "k-lg:pl-[7%]", "k-lg:pr-[20%]"]
おそらくPrettierで改行されないように配列化したものと思われますが、そもそも一つの文字列で（通常の`className`のように）書いても動作するのでそちらをお勧めします。
配列にしても中身が増えてくると結局折り返されるので、一つの文字列にまとめた方が確実です。

2021-10-16 15:41 UTC, kazuhiro-f requested changes
* `Header`が無いので検証しづらかったと思いますが、PC画面で`Footer`の内容が`Header`に隠れてしまいます。
* 情報の共有不足で申し訳ないのですが、PR#22で`html`に昨年のものと同様のフォントサイズを指定しました。したがって`rem`が変わりこちらのフォントサイズにも影響が出ますので修正をお願いします。（スタイルは基本的に去年のコードを適宜リファクタしながら写経する感じが良いと思います（特に`px`や`rem`の数値））

`Header`のレイアウトがちょっと特殊で、`page`と`Footer`が画面いっぱいに広がっているレイヤーの上に`Header`のレイヤーがある感じになっています。
したがって`Footer`も、基本的には`ml-auto`で右寄せにして、調整は`pr`など右側の数値だけで済ませる、というイレギュラーな感じになっていたと思います。
そのあたりは昨年のソースを読んで察してやるしかないのがつらいところですが、よろしくお願いします。

2021-10-16 15:41 UTC, kazuhiro-f commented on src/components/modules/Footer/Footer.tsx
> +        ["k-lg:text-[1.35rem]", "k-lg:py-[5%]", "k-lg:pl-[7%]", "k-lg:pr-[20%]"]
おそらくPrettierで改行されないように配列化したものと思われますが、そもそも一つの文字列で（通常の`className`のように）書いても動作するのでそちらをお勧めします。
配列にしても中身が増えてくると結局折り返されるので、一つの文字列にまとめた方が確実です。
```
className={clsx(
  "bg-k-navy-black",
  "text-white",
  "text-[1.125rem] px-[10%] pt-[10%] pb-[130px]",
  "k-lg:text-[1.35rem] k-lg:py-[5%] k-lg:pl-[7%] k-lg:pr-[20%]"
)}
```

2021-10-16 15:41 UTC, kazuhiro-f commented on src/components/modules/Footer/Footer.tsx
> +};
これは好みの問題ですが、`pageURL`をまとめてもコードの記述量的にはあまり意味が無いように思います。
`Link`を`map`で書くのであれば`a`のテキストもまとめる必要がありますし、今回は`Link`をベタ書きしているので`pageURL`をまとめてもDRYにならず、それならむしろ`Link`内で都度書いた方が読みやすいように思います。

何か意図があってこのように書いているのであれば問題ありません。

2021-10-17 01:49 UTC, minusvoid commented
[ヘッダーとの位置関係について](https://github.com/kougakusai/kougakusai-hp/pull/20#pullrequestreview-781367595)Layoutで調整（glidとか、順序をつけて）するつもりでしたが、右寄せの方法で修正するようにします。

2021-10-17 01:51 UTC, minusvoid commented on src/components/modules/Footer/Footer.tsx
> +        ["k-lg:text-[1.35rem]", "k-lg:py-[5%]", "k-lg:pl-[7%]", "k-lg:pr-[20%]"]
要素の数が多かったので、可読性や保守性のためにまとめてました（本来なら、普通に`className`に書けばよい）。修正しておきます。

2021-10-17 01:53 UTC, minusvoid commented on src/components/modules/Footer/Footer.tsx
> +};
後にリンクを書くときに（リンクが変わることはないだろうけど）楽なように（ページが増えたりしても）してました。特に意味はありません。

2021-10-17 01:57 UTC, minusvoid commented
頂いたコメントで、フォントサイズが揃わない原因が分かりました。修正しておきます。

2021-10-17 02:28 UTC, minusvoid commented on src/components/modules/Footer/Footer.tsx
> +};
`Header`と同様の記法へ変更しました。

2021-10-17 03:00 UTC, kazuhiro-f requested changes
右寄せになりましたが、`aboslute`、`bottom-0`、`right-0`で右寄せにすると、おそらく画面内で位置が固定されてしまい、コンテンツの下に配置される本来の動作とは異なってしまうかと思います。

`index`以外のページ（404ページ）で見ると分かりやすいと思いますが、今のコードだとコンテンツの長さに関係なく画面最下部固定になります。
試しに`absolute bottom-0 k-lg:right-0`を`k-lg:ml-auto`に変更すると404ページのコンテンツの下にフッターが続く形になるはずです。

また、こちらも`absolute`による副作用だと思われますが、モバイル画面でフッターの高さが異なる気がします。
昨年度版では`margin-bottom`が無視されて下側は`padding`分しか高さがないのに対し、このコードでは`mb`と`pb`の分の高さがある状態になっていました。

2021-10-17 03:22 UTC, minusvoid commented on src/components/modules/Footer/Footer.tsx
> +    <footer className="mb-[104px] k-lg:mb-0 w-full k-lg:w-[calc(100%-20vw)] bg-k-navy-black text-white text-[1.8rem] px-[10%] pt-[10%] pb-[130px] k-lg:py-[5%] k-lg:pl-[7%] k-lg:pr-[20%] absolute bott
こちらの理解が足りなかった。

2021-10-17 03:30 UTC, minusvoid commented
確認よろしくお願いします。

> `absolute` 修正

`kg:ml-auto`で修正済。

> モバイル表示：下部余白

モバイルヘッダーの常に表示される帯分の`mb`のつもりでしたが、不要でした（昨年度は入ってる？）。

2021-10-17 05:13 UTC, kazuhiro-f commented
`mb`を調べてみたところ、`index`ではなぜか`margin-bottom`が無いのに対して、他のページでは`margin-bottom`が入っていますね（こちらを見落としていました、申し訳ありません）。
`mb`が入っていなくてもフッターの内容は全部見えますが、`mb`を入れた方が良いのかもしれません。判断はお任せします。

2021-10-17 05:13 UTC, kazuhiro-f approved these changes
LGTM.
対応ありがとうございました。

2021-10-17 05:25 UTC, merged